# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - app-service-test1 (slot: pp)

on:
  push:
    branches:
      - pp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DotNetCore8DemoBurnApp.csproj

      - name: Build project
        run: dotnet build DotNetCore8DemoBurnApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish DotNetCore8DemoBurnApp.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: burn-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'pp'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published app from build job
        uses: actions/download-artifact@v4
        with:
          name: burn-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3FE0E95482FB40A197CE9DB86EAF0BE2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6E2BDB00BAB04CC8956A3F4162D917F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCC7DF4524B94B5B838FD71CC553A318 }}

      - name: Deploy to Azure Web App (slot: pp)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-service-test1'
          slot-name: 'pp'
          package: ./burn-app
